CREATE DATABASE SENAI_PRODUTOS_TARDE;

USE SENAI_PRODUTOS_TARDE;

CREATE TABLE PRODUTOS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	DESCRICAO TEXT NOT NULL
);

insert into produtos(nome, DESCRICAO)
	values ('Ariel', 'Melhor sabão já feito.');